name: portfolio_danish
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  universal_html: ^2.2.4
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  firebase_core: ^3.12.1
  flutter_mailer: ^3.0.0
  cloud_firestore: ^5.6.5
  http: ^1.3.0
  url_launcher: ^6.3.1
  firebase_remote_config: ^5.4.2
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700