// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlP7q48BVs0XDSaZcqaIQNDJbdSLKcwB8',
    appId: '1:914590044736:web:0312ba178faf1a718a85a5',
    messagingSenderId: '914590044736',
    projectId: 'portfolio-61271',
    authDomain: 'portfolio-61271.firebaseapp.com',
    storageBucket: 'portfolio-61271.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPgN-akeCz998ahUo0_czgH4FWch3Tkts',
    appId: '1:914590044736:android:3d055492552d32618a85a5',
    messagingSenderId: '914590044736',
    projectId: 'portfolio-61271',
    storageBucket: 'portfolio-61271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1uy16VUzInQ0dK76adBB7HH6xjk5t2mE',
    appId: '1:914590044736:ios:d41c87ce2bfe0a8d8a85a5',
    messagingSenderId: '914590044736',
    projectId: 'portfolio-61271',
    storageBucket: 'portfolio-61271.firebasestorage.app',
    iosBundleId: 'com.example.portfolioDanish',
  );

}